# Generated by Django 4.2.27 on 2025-12-21 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="店铺名称"),
                ),
                (
                    "shop_category",
                    models.CharField(
                        choices=[
                            ("convenience", "便利店"),
                            ("catering", "餐饮"),
                            ("beauty", "美容美发"),
                            ("housekeeping", "家政服务"),
                            ("repair", "维修服务"),
                            ("bakery", "烘焙"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="店铺分类",
                    ),
                ),
                (
                    "shop_phone",
                    models.CharField(max_length=15, verbose_name="联系电话"),
                ),
                (
                    "shop_address",
                    models.CharField(max_length=200, verbose_name="店铺地址"),
                ),
                (
                    "shop_description",
                    models.TextField(max_length=500, verbose_name="店铺介绍"),
                ),
                ("business_hours_start", models.TimeField(verbose_name="营业开始时间")),
                ("business_hours_end", models.TimeField(verbose_name="营业结束时间")),
                (
                    "business_license",
                    models.ImageField(
                        upload_to="merchant/licenses/", verbose_name="营业执照"
                    ),
                ),
                (
                    "identity_card_front",
                    models.ImageField(
                        upload_to="merchant/identities/", verbose_name="身份证正面"
                    ),
                ),
                (
                    "identity_card_back",
                    models.ImageField(
                        upload_to="merchant/identities/", verbose_name="身份证背面"
                    ),
                ),
                (
                    "other_certificates",
                    models.JSONField(blank=True, default=list, verbose_name="其他证件"),
                ),
                (
                    "legal_name",
                    models.CharField(max_length=50, verbose_name="法人姓名"),
                ),
                (
                    "legal_id_card",
                    models.CharField(max_length=18, verbose_name="法人身份证号"),
                ),
                (
                    "legal_phone",
                    models.CharField(max_length=15, verbose_name="法人手机号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="审核意见"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_merchant_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核员",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商户入驻申请",
                "verbose_name_plural": "商户入驻申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=100, verbose_name="店铺名称"),
                ),
                (
                    "shop_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="merchant/logos/",
                        verbose_name="店铺Logo",
                    ),
                ),
                (
                    "shop_category",
                    models.CharField(max_length=20, verbose_name="店铺分类"),
                ),
                (
                    "shop_phone",
                    models.CharField(max_length=15, verbose_name="联系电话"),
                ),
                (
                    "shop_address",
                    models.CharField(max_length=200, verbose_name="店铺地址"),
                ),
                (
                    "shop_description",
                    models.TextField(max_length=500, verbose_name="店铺介绍"),
                ),
                (
                    "shop_announcement",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="店铺公告"
                    ),
                ),
                ("business_hours_start", models.TimeField(verbose_name="营业开始时间")),
                ("business_hours_end", models.TimeField(verbose_name="营业结束时间")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="总订单数"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="总收入",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.merchantapplication",
                        verbose_name="关联申请",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商户档案",
                "verbose_name_plural": "商户档案",
                "ordering": ["-created_at"],
            },
        ),
    ]
