# Generated by Django 4.2.27 on 2025-12-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="商品描述"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="merchant/products/",
                        verbose_name="商品图片",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("饮品", "饮品"),
                            ("甜品", "甜品"),
                            ("烘焙", "烘焙"),
                            ("家政服务", "家政服务"),
                            ("便民服务", "便民服务"),
                            ("其他", "其他"),
                        ],
                        max_length=20,
                        verbose_name="商品分类",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="售价"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="原价",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存")),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "上架中"), ("offline", "已下架")],
                        default="online",
                        max_length=10,
                        verbose_name="上架状态",
                    ),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="销售数量"),
                ),
                (
                    "service_time_slots",
                    models.JSONField(blank=True, default=list, verbose_name="服务时段"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="merchant.merchantprofile",
                        verbose_name="所属商户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品/服务",
                "verbose_name_plural": "商品/服务",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "status"],
                        name="merchant_me_merchan_9e7192_idx",
                    ),
                    models.Index(
                        fields=["category"], name="merchant_me_categor_31195a_idx"
                    ),
                ],
            },
        ),
    ]
