# Generated by Django 4.2.27 on 2025-12-21 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("merchant", "0002_merchantproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="优惠券名称")),
                (
                    "description",
                    models.TextField(max_length=300, verbose_name="使用说明"),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("discount", "减价券"),
                            ("deduction", "满减券"),
                            ("gift", "赠品券"),
                        ],
                        max_length=20,
                        verbose_name="券类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="优惠金额"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="最低消费金额",
                    ),
                ),
                ("total_count", models.PositiveIntegerField(verbose_name="发行数量")),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="已使用数量"),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        default=1, verbose_name="每用户限领数量"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="开始时间")),
                ("end_date", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "生效中"),
                            ("inactive", "已停用"),
                            ("expired", "已过期"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="merchant.merchantprofile",
                        verbose_name="所属商户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商户优惠券",
                "verbose_name_plural": "商户优惠券",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=32, unique=True, verbose_name="订单号"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总金额"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="实付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新订单"),
                            ("accepted", "已接单"),
                            ("preparing", "准备中"),
                            ("ready", "待取餐"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "pickup_type",
                    models.CharField(
                        choices=[("pickup", "到店自取"), ("delivery", "外送")],
                        default="pickup",
                        max_length=20,
                        verbose_name="取餐方式",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=50, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=15, verbose_name="联系电话"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="送餐地址"
                    ),
                ),
                (
                    "pickup_code",
                    models.CharField(blank=True, max_length=6, verbose_name="取餐码"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="优惠金额",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="订单备注"
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(
                        blank=True, max_length=200, verbose_name="拒单原因"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="下单时间"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接单时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="merchant.merchantprofile",
                        verbose_name="商户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商户订单",
                "verbose_name_plural": "商户订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=20,
                        verbose_name="使用状态",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(max_length=32, unique=True, verbose_name="核销码"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.merchantcoupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "used_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="merchant.merchantorder",
                        verbose_name="使用订单",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="商品名称"),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="商品单价"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="购买数量")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="小计金额"
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(blank=True, default=dict, verbose_name="商品规格"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="merchant.merchantorder",
                        verbose_name="订单",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.merchantproduct",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单商品",
                "verbose_name_plural": "订单商品",
            },
        ),
        migrations.AddField(
            model_name="merchantorder",
            name="used_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.usercoupon",
                verbose_name="使用的优惠券",
            ),
        ),
        migrations.AddField(
            model_name="merchantorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="下单用户",
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["user", "status"], name="merchant_us_user_id_8e1429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercoupon",
            index=models.Index(
                fields=["verification_code"], name="merchant_us_verific_5f957b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercoupon",
            unique_together={("user", "coupon")},
        ),
        migrations.AddIndex(
            model_name="merchantorder",
            index=models.Index(
                fields=["merchant", "status"], name="merchant_me_merchan_6260f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantorder",
            index=models.Index(
                fields=["user", "status"], name="merchant_me_user_id_d3dc28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantorder",
            index=models.Index(
                fields=["pickup_code"], name="merchant_me_pickup__de9f97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantorder",
            index=models.Index(
                fields=["order_no"], name="merchant_me_order_n_326463_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantcoupon",
            index=models.Index(
                fields=["merchant", "status"], name="merchant_me_merchan_ed3828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantcoupon",
            index=models.Index(
                fields=["start_date", "end_date"], name="merchant_me_start_d_a2ffca_idx"
            ),
        ),
    ]
