# Generated by Django 4.2.27 on 2026-01-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0003_merchantcoupon_merchantorder_usercoupon_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercoupon",
            unique_together=set(),
        ),
    ]
