# Generated by Django 4.2.27 on 2025-12-18 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="楼栋名称")),
            ],
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=10, verbose_name="单元号")),
                ("floor", models.IntegerField(verbose_name="楼层")),
                ("room_number", models.CharField(max_length=10, verbose_name="门牌号")),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="面积"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(default=1, verbose_name="房屋状态"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.building",
                        verbose_name="所属楼栋",
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "unit", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="HouseBindingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(max_length=20, verbose_name="申请人姓名"),
                ),
                (
                    "applicant_phone",
                    models.CharField(max_length=15, verbose_name="申请人手机号"),
                ),
                (
                    "id_card_number",
                    models.CharField(max_length=18, verbose_name="身份证号"),
                ),
                (
                    "community_name",
                    models.CharField(
                        default="阳光花园", max_length=100, verbose_name="社区名称"
                    ),
                ),
                ("building_name", models.CharField(max_length=50, verbose_name="楼栋")),
                ("unit_name", models.CharField(max_length=20, verbose_name="单元")),
                ("room_number", models.CharField(max_length=20, verbose_name="房号")),
                (
                    "identity",
                    models.SmallIntegerField(
                        choices=[(1, "业主"), (2, "家庭成员"), (3, "租客")],
                        default=1,
                        verbose_name="申请身份",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "已通过"), (2, "已拒绝")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "audit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                ("audit_remark", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="拒绝原因"
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audited_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "房屋绑定申请",
                "verbose_name_plural": "房屋绑定申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HouseUserBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity",
                    models.SmallIntegerField(
                        choices=[(1, "业主"), (2, "家庭成员"), (3, "租客")],
                        default=1,
                        verbose_name="住户身份",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "已绑定"), (2, "已解绑")],
                        default=1,
                        verbose_name="绑定状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.housebindingapplication",
                        verbose_name="关联申请",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_bindings",
                        to="property.house",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_bindings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "住户绑定记录",
                "verbose_name_plural": "住户绑定记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
