# Generated by Django 4.2.27 on 2025-12-18 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="访客姓名")),
                ("phone", models.CharField(max_length=15, verbose_name="访客手机号")),
                (
                    "car_number",
                    models.CharField(blank=True, max_length=20, verbose_name="车牌号"),
                ),
                ("visit_time", models.DateTimeField(verbose_name="访问时间")),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待访问"),
                            ("visited", "已访问"),
                            ("expired", "已过期"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "qr_code_token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="二维码令牌"
                    ),
                ),
                (
                    "qr_code_expires_at",
                    models.DateTimeField(verbose_name="二维码过期时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "visit_actual_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际访问时间"
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "访客邀请",
                "verbose_name_plural": "访客邀请",
                "ordering": ["-created_at"],
            },
        ),
    ]
