# Generated by Django 4.2.27 on 2025-12-19 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0002_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingBindingApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=20, verbose_name="车主姓名"),
                ),
                (
                    "owner_phone",
                    models.CharField(max_length=15, verbose_name="车主手机号"),
                ),
                ("id_card", models.CharField(max_length=18, verbose_name="身份证号")),
                (
                    "community_name",
                    models.CharField(
                        default="阳光花园", max_length=100, verbose_name="社区名称"
                    ),
                ),
                (
                    "parking_type",
                    models.CharField(
                        choices=[("owned", "自有车位"), ("rented", "租赁车位")],
                        default="owned",
                        max_length=10,
                        verbose_name="车位类型",
                    ),
                ),
                (
                    "parking_area",
                    models.CharField(max_length=50, verbose_name="停车区域"),
                ),
                ("parking_no", models.CharField(max_length=20, verbose_name="车位号")),
                ("car_no", models.CharField(max_length=20, verbose_name="车牌号")),
                (
                    "car_brand",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="车辆品牌"
                    ),
                ),
                (
                    "car_color",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="车辆颜色"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "待审核"), (1, "已通过"), (2, "已拒绝")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "audit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                ("audit_remark", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "reject_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="拒绝原因"
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audited_parking_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "车位绑定申请",
                "verbose_name_plural": "车位绑定申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParkingSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=50, verbose_name="停车区域")),
                (
                    "space_number",
                    models.CharField(max_length=20, verbose_name="车位号"),
                ),
                (
                    "parking_type",
                    models.CharField(
                        choices=[("owned", "自有车位"), ("rented", "租赁车位")],
                        default="owned",
                        max_length=10,
                        verbose_name="车位类型",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(default=1, verbose_name="车位状态"),
                ),
            ],
            options={
                "verbose_name": "车位",
                "verbose_name_plural": "车位",
                "unique_together": {("area_name", "space_number")},
            },
        ),
        migrations.CreateModel(
            name="ParkingUserBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "已绑定"), (2, "已解绑")],
                        default=1,
                        verbose_name="绑定状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.parkingbindingapplication",
                        verbose_name="关联申请",
                    ),
                ),
                (
                    "parking_space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_bindings",
                        to="property.parkingspace",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_bindings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "车位绑定记录",
                "verbose_name_plural": "车位绑定记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
