# Generated by Django 4.2.27 on 2025-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_parkingbindingapplication_parkingspace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingbindingapplication",
            name="identity",
            field=models.SmallIntegerField(
                choices=[(1, "业主"), (3, "租客")], default=1, verbose_name="申请身份"
            ),
        ),
        migrations.AddField(
            model_name="parkinguserbinding",
            name="identity",
            field=models.SmallIntegerField(
                choices=[(1, "业主"), (3, "租客")], default=1, verbose_name="绑定身份"
            ),
        ),
    ]
