# Generated by Django 4.2.27 on 2025-12-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0004_parkingbindingapplication_identity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("all", "全员"), ("building", "指定楼栋")],
                        default="all",
                        max_length=20,
                        verbose_name="发送范围",
                    ),
                ),
                (
                    "target_buildings",
                    models.JSONField(blank=True, null=True, verbose_name="目标楼栋"),
                ),
                (
                    "author_name",
                    models.CharField(max_length=50, verbose_name="作者姓名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="撤回时间"
                    ),
                ),
                ("read_count", models.IntegerField(default=0, verbose_name="阅读次数")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-created_at"],
            },
        ),
    ]
