# Generated by Django 4.2.27 on 2025-12-20 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0005_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
    ]
