# Generated by Django 4.2.27 on 2025-12-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0006_alter_announcement_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("property_notice", "物业通知"),
                    ("community_news", "社区新闻"),
                    ("warm_tips", "温馨提示"),
                ],
                default="property_notice",
                max_length=20,
                verbose_name="公告分类",
            ),
        ),
    ]
