# Generated by Django 4.2.27 on 2025-12-21 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0008_repairemployee_repairorder_repairorderimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="收费项目名称")),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("property", "物业费"),
                            ("parking", "停车费"),
                            ("water", "水费"),
                            ("electric", "电费"),
                            ("gas", "燃气费"),
                            ("heating", "供暖费"),
                        ],
                        max_length=20,
                        verbose_name="费用类型",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "billing_unit",
                    models.CharField(
                        choices=[
                            ("per_sqm_month", "元/平米/月"),
                            ("per_month", "元/月"),
                            ("per_unit", "元/单位"),
                            ("per_degree", "元/度"),
                        ],
                        default="per_sqm_month",
                        max_length=20,
                        verbose_name="计费单位",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("description", models.TextField(blank=True, verbose_name="收费说明")),
                (
                    "target_buildings",
                    models.JSONField(blank=True, null=True, verbose_name="适用楼栋"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "收费标准",
                "verbose_name_plural": "收费标准",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_no",
                    models.CharField(max_length=32, unique=True, verbose_name="账单号"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="账单标题")),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("property", "物业费"),
                            ("parking", "停车费"),
                            ("water", "水费"),
                            ("electric", "电费"),
                            ("gas", "燃气费"),
                            ("heating", "供暖费"),
                        ],
                        max_length=20,
                        verbose_name="费用类型",
                    ),
                ),
                ("billing_period_start", models.DateField(verbose_name="计费周期开始")),
                ("billing_period_end", models.DateField(verbose_name="计费周期结束")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="计费数量",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="应缴金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "待支付"),
                            ("paid", "已支付"),
                            ("overdue", "已逾期"),
                            ("cancelled", "已取消"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="账单状态",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="缴费截止日期")),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="已缴金额",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("cash", "现金"),
                            ("transfer", "转账"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="支付流水号"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="账单说明")),
                (
                    "admin_remark",
                    models.TextField(blank=True, verbose_name="管理员备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "fee_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="property.feestandard",
                        verbose_name="收费标准",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="property.house",
                        verbose_name="关联房屋",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="缴费人",
                    ),
                ),
            ],
            options={
                "verbose_name": "账单",
                "verbose_name_plural": "账单",
                "ordering": ["-created_at"],
                "unique_together": {
                    ("house", "fee_type", "billing_period_start", "billing_period_end")
                },
            },
        ),
    ]
