# Generated by Django 4.2.27 on 2025-12-22 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0009_feestandard_bill"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(max_length=100, verbose_name="人员姓名"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("face", "人脸识别"),
                            ("qrcode", "二维码"),
                            ("card", "刷卡"),
                            ("password", "密码"),
                        ],
                        max_length=20,
                        verbose_name="开门方式",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "进入"), ("out", "离开")],
                        default="in",
                        max_length=10,
                        verbose_name="进出方向",
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="位置")),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("resident", "业主"),
                            ("visitor", "访客"),
                            ("delivery", "配送员"),
                            ("staff", "工作人员"),
                            ("other", "其他"),
                        ],
                        default="resident",
                        max_length=20,
                        verbose_name="人员类型",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, max_length=50, verbose_name="设备ID"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "门禁日志",
                "verbose_name_plural": "门禁日志",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="property_ac_timesta_6f2f98_idx"
                    ),
                    models.Index(
                        fields=["person_name"], name="property_ac_person__8613e2_idx"
                    ),
                    models.Index(
                        fields=["method"], name="property_ac_method_6ae38c_idx"
                    ),
                    models.Index(
                        fields=["location"], name="property_ac_locatio_258264_idx"
                    ),
                    models.Index(
                        fields=["person_type"], name="property_ac_person__9297e7_idx"
                    ),
                ],
            },
        ),
    ]
