/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/merchant': RouteRecordInfo<'/merchant', '/merchant', Record<never, never>, Record<never, never>, '/merchant/dashboard' | '/merchant/orders' | '/merchant/products' | '/merchant/settings'>,
    '/merchant/dashboard': RouteRecordInfo<'/merchant/dashboard', '/merchant/dashboard', Record<never, never>, Record<never, never>>,
    '/merchant/orders': RouteRecordInfo<'/merchant/orders', '/merchant/orders', Record<never, never>, Record<never, never>>,
    '/merchant/products': RouteRecordInfo<'/merchant/products', '/merchant/products', Record<never, never>, Record<never, never>>,
    '/merchant/settings': RouteRecordInfo<'/merchant/settings', '/merchant/settings', Record<never, never>, Record<never, never>>,
    '/merchant-register': RouteRecordInfo<'/merchant-register', '/merchant-register', Record<never, never>, Record<never, never>>,
    '/property': RouteRecordInfo<'/property', '/property', Record<never, never>, Record<never, never>, '/property/access-logs' | '/property/activities' | '/property/announcements' | '/property/dashboard' | '/property/employees' | '/property/fees' | '/property/houses' | '/property/merchant-audit' | '/property/parking' | '/property/parking-audit' | '/property/residents/' | '/property/residents/audit' | '/property/work-orders'>,
    '/property/access-logs': RouteRecordInfo<'/property/access-logs', '/property/access-logs', Record<never, never>, Record<never, never>>,
    '/property/activities': RouteRecordInfo<'/property/activities', '/property/activities', Record<never, never>, Record<never, never>>,
    '/property/announcements': RouteRecordInfo<'/property/announcements', '/property/announcements', Record<never, never>, Record<never, never>>,
    '/property/dashboard': RouteRecordInfo<'/property/dashboard', '/property/dashboard', Record<never, never>, Record<never, never>>,
    '/property/employees': RouteRecordInfo<'/property/employees', '/property/employees', Record<never, never>, Record<never, never>>,
    '/property/fees': RouteRecordInfo<'/property/fees', '/property/fees', Record<never, never>, Record<never, never>>,
    '/property/houses': RouteRecordInfo<'/property/houses', '/property/houses', Record<never, never>, Record<never, never>>,
    '/property/merchant-audit': RouteRecordInfo<'/property/merchant-audit', '/property/merchant-audit', Record<never, never>, Record<never, never>>,
    '/property/parking': RouteRecordInfo<'/property/parking', '/property/parking', Record<never, never>, Record<never, never>>,
    '/property/parking-audit': RouteRecordInfo<'/property/parking-audit', '/property/parking-audit', Record<never, never>, Record<never, never>>,
    '/property/residents/': RouteRecordInfo<'/property/residents/', '/property/residents', Record<never, never>, Record<never, never>>,
    '/property/residents/audit': RouteRecordInfo<'/property/residents/audit', '/property/residents/audit', Record<never, never>, Record<never, never>>,
    '/property/work-orders': RouteRecordInfo<'/property/work-orders', '/property/work-orders', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/merchant.vue': {
      routes: '/merchant' | '/merchant/dashboard' | '/merchant/orders' | '/merchant/products' | '/merchant/settings'
      views: 'default'
    }
    'src/pages/merchant/dashboard.vue': {
      routes: '/merchant/dashboard'
      views: never
    }
    'src/pages/merchant/orders.vue': {
      routes: '/merchant/orders'
      views: never
    }
    'src/pages/merchant/products.vue': {
      routes: '/merchant/products'
      views: never
    }
    'src/pages/merchant/settings.vue': {
      routes: '/merchant/settings'
      views: never
    }
    'src/pages/merchant-register.vue': {
      routes: '/merchant-register'
      views: never
    }
    'src/pages/property.vue': {
      routes: '/property' | '/property/residents/' | '/property/access-logs' | '/property/activities' | '/property/announcements' | '/property/residents/audit' | '/property/dashboard' | '/property/employees' | '/property/fees' | '/property/houses' | '/property/merchant-audit' | '/property/parking' | '/property/parking-audit' | '/property/residents' | '/property/work-orders'
      views: 'default'
    }
    'src/pages/property/access-logs.vue': {
      routes: '/property/access-logs'
      views: never
    }
    'src/pages/property/activities.vue': {
      routes: '/property/activities'
      views: never
    }
    'src/pages/property/announcements.vue': {
      routes: '/property/announcements'
      views: never
    }
    'src/pages/property/dashboard.vue': {
      routes: '/property/dashboard'
      views: never
    }
    'src/pages/property/employees.vue': {
      routes: '/property/employees'
      views: never
    }
    'src/pages/property/fees.vue': {
      routes: '/property/fees'
      views: never
    }
    'src/pages/property/houses.vue': {
      routes: '/property/houses'
      views: never
    }
    'src/pages/property/merchant-audit.vue': {
      routes: '/property/merchant-audit'
      views: never
    }
    'src/pages/property/parking.vue': {
      routes: '/property/parking'
      views: never
    }
    'src/pages/property/parking-audit.vue': {
      routes: '/property/parking-audit'
      views: never
    }
    'src/pages/property/residents/index.vue': {
      routes: '/property/residents/'
      views: never
    }
    'src/pages/property/residents/audit.vue': {
      routes: '/property/residents/audit'
      views: never
    }
    'src/pages/property/work-orders.vue': {
      routes: '/property/work-orders'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
