# Generated by Django 4.2.27 on 2025-12-19 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="商品标题")),
                ("description", models.TextField(verbose_name="商品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("家用电器", "家用电器"),
                            ("家具", "家具"),
                            ("数码产品", "数码产品"),
                            ("图书音像", "图书音像"),
                            ("服装鞋包", "服装鞋包"),
                            ("母婴用品", "母婴用品"),
                            ("运动户外", "运动户外"),
                            ("其他", "其他"),
                        ],
                        max_length=50,
                        verbose_name="商品类别",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("全新", "全新"),
                            ("99新", "99新"),
                            ("95新", "95新"),
                            ("9成新", "9成新"),
                            ("8成新", "8成新"),
                            ("7成新", "7成新"),
                        ],
                        max_length=20,
                        verbose_name="成色",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[
                            ("自提", "自提"),
                            ("同城配送", "同城配送"),
                            ("快递邮寄", "快递邮寄"),
                        ],
                        max_length=50,
                        verbose_name="交易方式",
                    ),
                ),
                (
                    "is_sold",
                    models.BooleanField(default=False, verbose_name="是否已售出"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "favorite_count",
                    models.PositiveIntegerField(default=0, verbose_name="收藏次数"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="卖家",
                    ),
                ),
            ],
            options={
                "verbose_name": "二手商品",
                "verbose_name_plural": "二手商品管理",
                "db_table": "community_market_item",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NeighborHelpPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="求助标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="求助内容")),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("急", "急"),
                            ("借物", "借物"),
                            ("寻物", "寻物"),
                            ("帮忙", "帮忙"),
                        ],
                        max_length=20,
                        verbose_name="标签",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="联系电话"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="位置"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="是否紧急"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="是否已解决"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "response_count",
                    models.PositiveIntegerField(default=0, verbose_name="回复数量"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "互助求助帖",
                "verbose_name_plural": "互助求助帖管理",
                "db_table": "community_help_post",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="market_items/", verbose_name="图片"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="community.marketitem",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片管理",
                "db_table": "community_market_item_image",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HelpResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="回复内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="回复时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "help_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="community.neighborhelppost",
                        verbose_name="求助帖",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回复者",
                    ),
                ),
            ],
            options={
                "verbose_name": "求助回复",
                "verbose_name_plural": "求助回复管理",
                "db_table": "community_help_response",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpPostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="help_posts/", verbose_name="图片"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="community.neighborhelppost",
                        verbose_name="求助帖",
                    ),
                ),
            ],
            options={
                "verbose_name": "求助帖图片",
                "verbose_name_plural": "求助帖图片管理",
                "db_table": "community_help_post_image",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("image", "图片"),
                            ("system", "系统消息"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "market_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="community.marketitem",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "私聊消息",
                "verbose_name_plural": "私聊消息管理",
                "db_table": "community_chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketItemFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="community.marketitem",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品收藏",
                "verbose_name_plural": "商品收藏管理",
                "db_table": "community_market_item_favorite",
                "unique_together": {("user", "item")},
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_message_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="最后消息时间"
                    ),
                ),
                (
                    "unread_count_p1",
                    models.PositiveIntegerField(
                        default=0, verbose_name="参与者1未读数"
                    ),
                ),
                (
                    "unread_count_p2",
                    models.PositiveIntegerField(
                        default=0, verbose_name="参与者2未读数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="community.chatmessage",
                        verbose_name="最后一条消息",
                    ),
                ),
                (
                    "market_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="community.marketitem",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "participant1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_p1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与者1",
                    ),
                ),
                (
                    "participant2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_p2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与者2",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天会话",
                "verbose_name_plural": "聊天会话管理",
                "db_table": "community_chat_conversation",
                "ordering": ["-last_message_time"],
                "unique_together": {("participant1", "participant2", "market_item")},
            },
        ),
    ]
