# Generated by Django 4.2.27 on 2025-12-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketitem",
            name="trade_type",
        ),
    ]
