# Generated by Django 4.2.27 on 2025-12-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_remove_marketitem_trade_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动名称")),
                ("description", models.TextField(verbose_name="活动描述")),
                ("location", models.CharField(max_length=200, verbose_name="活动地点")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=50, verbose_name="最大参与人数"
                    ),
                ),
                (
                    "current_participants",
                    models.PositiveIntegerField(default=0, verbose_name="当前参与人数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "即将开始"),
                            ("ongoing", "进行中"),
                            ("ended", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="活动状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "require_approval",
                    models.BooleanField(default=False, verbose_name="是否需要审核"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="组织者",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区活动",
                "verbose_name_plural": "社区活动管理",
                "db_table": "community_activity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="activity_images/", verbose_name="图片"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="community.activity",
                        verbose_name="活动",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动图片",
                "verbose_name_plural": "活动图片管理",
                "db_table": "community_activity_image",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ActivityRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="approved",
                        max_length=20,
                        verbose_name="报名状态",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="联系电话"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="报名时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="community.activity",
                        verbose_name="活动",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动报名",
                "verbose_name_plural": "活动报名管理",
                "db_table": "community_activity_registration",
                "ordering": ["created_at"],
                "unique_together": {("activity", "user")},
            },
        ),
    ]
