# Generated by Django 4.2.27 on 2025-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_activity_activityimage_activityregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="require_approval",
        ),
        migrations.AlterField(
            model_name="activityregistration",
            name="status",
            field=models.CharField(
                choices=[("approved", "已报名"), ("cancelled", "已取消")],
                default="approved",
                max_length=20,
                verbose_name="报名状态",
            ),
        ),
    ]
