# Generated by Django 4.2.27 on 2026-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_remove_activity_require_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="activity_images/",
                verbose_name="活动封面图",
            ),
        ),
    ]
