# Generated by Django 4.2.27 on 2025-12-17 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_openid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "用户",
                "verbose_name_plural": "用户管理",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="详细地址"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ban_reason",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="禁用原因"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="城市"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="district",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="区县"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(
                choices=[(0, "未知"), (1, "男"), (2, "女")],
                default=0,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="是否被禁用"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="是否实名认证"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="最后登录IP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="昵称"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="province",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="省份"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="real_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="真实姓名"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="register_type",
            field=models.SmallIntegerField(
                choices=[(1, "手机注册"), (2, "微信注册"), (3, "后台创建")],
                default=1,
                verbose_name="注册方式",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, unique=True, verbose_name="手机号"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.SmallIntegerField(
                choices=[(0, "普通居民"), (1, "物业人员"), (2, "商户"), (3, "管理员")],
                default=0,
                verbose_name="角色",
            ),
        ),
    ]
