# Generated by Django 4.2.27 on 2025-12-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_user_address_user_ban_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="头像"
            ),
        ),
    ]
